version: "3.7"

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: gachi-api
    ports:
      - 3030:8080

  frontend:
    build:
      dockerfile: Dockerfile
      context: gachi-store
    depends_on:
     - backend
    ports:
      - 300:4200